-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object exposing (..)


type Address
    = Address


type Album
    = Album


type AlbumsPage
    = AlbumsPage


type Comment
    = Comment


type CommentsPage
    = CommentsPage


type Company
    = Company


type Geo
    = Geo


type PageLimitPair
    = PageLimitPair


type PageMetadata
    = PageMetadata


type PaginationLinks
    = PaginationLinks


type Photo
    = Photo


type PhotosPage
    = PhotosPage


type Post
    = Post


type PostsPage
    = PostsPage


type Todo
    = Todo


type TodosPage
    = TodosPage


type User
    = User


type UsersPage
    = UsersPage
