-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import PlaceholderApi.Scalar exposing (defaultCodecs)


type alias Id =
    PlaceholderApi.Scalar.Id


codecs : PlaceholderApi.Scalar.Codecs Id
codecs =
    PlaceholderApi.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
