-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.Address exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


street : SelectionSet (Maybe String) PlaceholderApi.Object.Address
street =
    Object.selectionForField "(Maybe String)" "street" [] (Decode.string |> Decode.nullable)


suite : SelectionSet (Maybe String) PlaceholderApi.Object.Address
suite =
    Object.selectionForField "(Maybe String)" "suite" [] (Decode.string |> Decode.nullable)


city : SelectionSet (Maybe String) PlaceholderApi.Object.Address
city =
    Object.selectionForField "(Maybe String)" "city" [] (Decode.string |> Decode.nullable)


zipcode : SelectionSet (Maybe String) PlaceholderApi.Object.Address
zipcode =
    Object.selectionForField "(Maybe String)" "zipcode" [] (Decode.string |> Decode.nullable)


geo :
    SelectionSet decodesTo PlaceholderApi.Object.Geo
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.Address
geo object____ =
    Object.selectionForCompositeField "geo" [] object____ (Basics.identity >> Decode.nullable)
