-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.Company exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


name : SelectionSet (Maybe String) PlaceholderApi.Object.Company
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


catchPhrase : SelectionSet (Maybe String) PlaceholderApi.Object.Company
catchPhrase =
    Object.selectionForField "(Maybe String)" "catchPhrase" [] (Decode.string |> Decode.nullable)


bs : SelectionSet (Maybe String) PlaceholderApi.Object.Company
bs =
    Object.selectionForField "(Maybe String)" "bs" [] (Decode.string |> Decode.nullable)
