-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.PaginationLinks exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


first :
    SelectionSet decodesTo PlaceholderApi.Object.PageLimitPair
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PaginationLinks
first object____ =
    Object.selectionForCompositeField "first" [] object____ (Basics.identity >> Decode.nullable)


prev :
    SelectionSet decodesTo PlaceholderApi.Object.PageLimitPair
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PaginationLinks
prev object____ =
    Object.selectionForCompositeField "prev" [] object____ (Basics.identity >> Decode.nullable)


next :
    SelectionSet decodesTo PlaceholderApi.Object.PageLimitPair
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PaginationLinks
next object____ =
    Object.selectionForCompositeField "next" [] object____ (Basics.identity >> Decode.nullable)


last :
    SelectionSet decodesTo PlaceholderApi.Object.PageLimitPair
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PaginationLinks
last object____ =
    Object.selectionForCompositeField "last" [] object____ (Basics.identity >> Decode.nullable)
