-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.Photo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


id : SelectionSet (Maybe PlaceholderApi.ScalarCodecs.Id) PlaceholderApi.Object.Photo
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (PlaceholderApi.ScalarCodecs.codecs |> PlaceholderApi.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


title : SelectionSet (Maybe String) PlaceholderApi.Object.Photo
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


url : SelectionSet (Maybe String) PlaceholderApi.Object.Photo
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)


thumbnailUrl : SelectionSet (Maybe String) PlaceholderApi.Object.Photo
thumbnailUrl =
    Object.selectionForField "(Maybe String)" "thumbnailUrl" [] (Decode.string |> Decode.nullable)


album :
    SelectionSet decodesTo PlaceholderApi.Object.Album
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.Photo
album object____ =
    Object.selectionForCompositeField "album" [] object____ (Basics.identity >> Decode.nullable)
