-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.PostsPage exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


data :
    SelectionSet decodesTo PlaceholderApi.Object.Post
    -> SelectionSet (Maybe (List (Maybe decodesTo))) PlaceholderApi.Object.PostsPage
data object____ =
    Object.selectionForCompositeField "data" [] object____ (Basics.identity >> Decode.nullable >> Decode.list >> Decode.nullable)


links :
    SelectionSet decodesTo PlaceholderApi.Object.PaginationLinks
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PostsPage
links object____ =
    Object.selectionForCompositeField "links" [] object____ (Basics.identity >> Decode.nullable)


meta :
    SelectionSet decodesTo PlaceholderApi.Object.PageMetadata
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.PostsPage
meta object____ =
    Object.selectionForCompositeField "meta" [] object____ (Basics.identity >> Decode.nullable)
