-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.Post exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


id : SelectionSet (Maybe PlaceholderApi.ScalarCodecs.Id) PlaceholderApi.Object.Post
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (PlaceholderApi.ScalarCodecs.codecs |> PlaceholderApi.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


title : SelectionSet (Maybe String) PlaceholderApi.Object.Post
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


body : SelectionSet (Maybe String) PlaceholderApi.Object.Post
body =
    Object.selectionForField "(Maybe String)" "body" [] (Decode.string |> Decode.nullable)


user :
    SelectionSet decodesTo PlaceholderApi.Object.User
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.Post
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)


type alias CommentsOptionalArguments =
    { options : OptionalArgument PlaceholderApi.InputObject.PageQueryOptions }


comments :
    (CommentsOptionalArguments -> CommentsOptionalArguments)
    -> SelectionSet decodesTo PlaceholderApi.Object.CommentsPage
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.Post
comments fillInOptionals____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { options = Absent }

        optionalArgs____ =
            [ Argument.optional "options" filledInOptionals____.options PlaceholderApi.InputObject.encodePageQueryOptions ]
                |> List.filterMap Basics.identity
    in
    Object.selectionForCompositeField "comments" optionalArgs____ object____ (Basics.identity >> Decode.nullable)
