-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module PlaceholderApi.Object.Todo exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import PlaceholderApi.InputObject
import PlaceholderApi.Interface
import PlaceholderApi.Object
import PlaceholderApi.Scalar
import PlaceholderApi.ScalarCodecs
import PlaceholderApi.Union


id : SelectionSet (Maybe PlaceholderApi.ScalarCodecs.Id) PlaceholderApi.Object.Todo
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (PlaceholderApi.ScalarCodecs.codecs |> PlaceholderApi.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


title : SelectionSet (Maybe String) PlaceholderApi.Object.Todo
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


completed : SelectionSet (Maybe Bool) PlaceholderApi.Object.Todo
completed =
    Object.selectionForField "(Maybe Bool)" "completed" [] (Decode.bool |> Decode.nullable)


user :
    SelectionSet decodesTo PlaceholderApi.Object.User
    -> SelectionSet (Maybe decodesTo) PlaceholderApi.Object.Todo
user object____ =
    Object.selectionForCompositeField "user" [] object____ (Basics.identity >> Decode.nullable)
